# 站点基础信息
site:
  tab: 我的博客
  title: 我的博客
  description: 一个清爽、快速、注重阅读体验的静态博客。
  language: en
  favicon: /favicon.ico
  theme:
    light: winter
    dark: dracula
    code: github-dark
  date_format: ddd MMM DD YYYY
  blog:
    pageSize: 8
  menu:
    - id: home
      text: 首页
      href: /
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: 关于
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: 文章
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
    - id: project
      text: 项目
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: 友链
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: contact
      text: 联系
      href: "mailto:contact.evesunmaple@outlook.com"
      target: _blank
      svg: "material-symbols:attach-email-outline-rounded"

# 作者信息
user:
  name: Jeffery
  email: "chow1784@gmail.com"
  site: "https://www.niceblog.xyz"
  avatar: /profile.png

  sidebar:
    social:
      - href: "/donate"
        ariaLabel: Solana 链打赏
        title: "Solana / USDT 打赏支持"
        svg: "ri:cup-line"
      - href: "https://github.com/slightyy?tab=repositories"
        ariaLabel: GitHub
        title: GitHub
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/256632366?spm_id_from=333.1007.0.0"
        ariaLabel: 哔哩哔哩
        title: 哔哩哔哩
        svg: "ri:bilibili-line"
      - href: "https://x.com/baggins69339049"
        ariaLabel: X 平台
        title: X (Twitter)
        svg: "ri:twitter-line"

  footer:
    social:
      - href: "/donate"
        ariaLabel: Solana 链打赏
        title: "Solana / USDT 打赏支持"
        svg: "ri:cup-line"
      - href: "https://github.com/slightyy?tab=repositories"
        ariaLabel: GitHub
        title: GitHub
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/256632366?spm_id_from=333.1007.0.0"
        ariaLabel: 哔哩哔哩
        title: 哔哩哔哩
        svg: "ri:bilibili-line"
      - href: "https://x.com/baggins69339049"
        ariaLabel: X 平台
        title: X (Twitter)
        svg: "ri:twitter-line"
